version: '3'

vars:
  entrypoint: main.go
  output: bin/digg

tasks:
  setup:
    cmds:
      - alias digg=./bin/digg

  clean:
    cmds:
      - rm -f {{.output}}

  build:
    deps:
      - clean
    cmds:
      - go build -o "{{.output}}" "{{.entrypoint}}"
